# Generated by Django 2.2.2 on 2020-11-03 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='タスク名')),
                ('day_limit', models.DateField(blank=True, null=True, verbose_name='期限日')),
                ('time_limit', models.TimeField(blank=True, null=True, verbose_name='時間の期限')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='補足情報')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
    ]
