# Generated by Django 2.2.2 on 2021-04-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
