# Generated by Django 2.2.2 on 2021-04-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20210407_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
