# Generated by Django 2.2.2 on 2020-10-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20201025_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='title',
        ),
    ]
