# Generated by Django 2.2.2 on 2020-10-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20201025_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
