# Generated by Django 2.2.2 on 2020-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_task_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
