# Generated by Django 2.2.2 on 2020-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20201025_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_limit',
            field=models.DateField(blank=True, null=True, verbose_name='期限日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='補足情報'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.TimeField(blank=True, null=True, verbose_name='時間の期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=140, verbose_name='タスク名'),
        ),
    ]
